version: '3'
services:
  git-sync:
    container_name: git-sync
    image: "ghcr.io/toobeeh/git-sync/git-sync:latest"
    ports:
      - 5000:5000
    environment:
      - REPO_URL=https://github.com/toobeeh/git-sync.git
      - WEBHOOK_SECRET=secret
    volumes:
      - ./repository:/app/repository