version: '3'
services:
  myrepo_updater:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - REPO_URL=https://github.com/toobeeh/git-sync.git
      - WEBHOOK_SECRET=secret
    volumes:
      - ./repository:/app/repository